### PR TITLE
Adding slot information to slurm config

### PR DESCRIPTION
**Pull request by mohanasudhan**
We are not using slot information which is passed
from compute node via sqs. Refer commit
https://github.com/awslabs/cfncluster-cookbook/commit/d9731ef184bca25de7b0f51e24b56c5d817fa854
on how number of slots is calculate. The change is
 in slurm config to set procs (cpus) as slots.
Refer https://slurm.schedmd.com/slurm.conf.html

Signed-off-by: Mohan Gandhi <mohgan@amazon.com>

Procs is alias to CPUs in slurm conf. If CPUs is omitted, it will be set equal to the product of Sockets, CoresPerSocket, and ThreadsPerCore.

== Testing ==
Currently i am figuring how to test. Modified slurm.py at /usr/local/lib/python2.7/dist-packages/sqswatcher/plugins/slurm.py but its not getting affected. still figuring how to test.

### CODE REVIEW

**Comment by rajachan** [comment]
A quick way to test this is to use extra_json and set `cfn_scheduler_slots` it to `cores` instead of the default `vcpus`, or pass a static value, and see if that changes the Procs value in your slurm.conf file.

```
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
```

**Comment by mohanasudhan** [comment]
I am confused here, even without my change values like SOCKETS, CORES, THREADS and CPUs are set correctly in slurm 

sinfo -o %all
AVAIL|ACTIVE_FEATURES|CPUS|TMP_DISK|FREE_MEM|AVAIL_FEATURES|GROUPS|OVERSUBSCRIBE|TIMELIMIT|MEMORY|HOSTNAMES|NODE_ADDR|PRIO_TIER|ROOT|JOB_SIZE|STATE|USER|VERSION|WEIGHT|S:C:T|NODES(A/I) |MAX_CPUS_PER_NODE |CPUS(A/I/O/T) |NODES |REASON |NODES(A/I/O/T) |GRES |TIMESTAMP |PRIO_JOB_FACTOR |DEFAULTTIME |PREEMPT_MODE |NODELIST |CPU_LOAD |PARTITION |PARTITION |ALLOCNODES |STATE |USER |SOCKETS |CORES |THREADS 
up|(null)|4|14983|N/A|(null)|all|NO|infinite|15038|ip-172-31-22-18|ip-172-31-22-18|1|no|1-infinite|unk*|root|N/A|1|1:2:2|0/1 |UNLIMITED |0/4/0/4 |1 |none |0/1/0/1 |(null) |Unknown |1 |n/a |OFF |ip-172-31-22-18 |N/A |compute* |compute |all |unknown* |root(0) |1 |2 |2 
up|(null)|4|14983|N/A|(null)|all|NO|infinite|15038|ip-172-31-29-209|ip-172-31-29-209|1|no|1-infinite|unk*|root|N/A|1|1:2:2|0/1 |UNLIMITED |0/4/0/4 |1 |none |0/1/0/1 |(null) |Unknown |1 |n/a |OFF |ip-172-31-29-209 |N/A |compute* |compute |all |unknown* |root(0) |1 |2 |2

**Comment by kgkeys** [comment]
Are you using the extra_json setting that @rajachan mentioned above? I'm using the same: 
`extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }`

My output is as follows:
sinfo -o %all
AVAIL|ACTIVE_FEATURES|CPUS|TMP_DISK|FREE_MEM|AVAIL_FEATURES|GROUPS|OVERSUBSCRIBE|TIMELIMIT|MEMORY|HOSTNAMES|NODE_ADDR|PRIO_TIER|ROOT|JOB_SIZE|STATE|USER|VERSION|WEIGHT|S:C:T|NODES(A/I) |MAX_CPUS_PER_NODE |CPUS(A/I/O/T) |NODES |REASON |NODES(A/I/O/T) |GRES |TIMESTAMP |PRIO_JOB_FACTOR |DEFAULTTIME |PREEMPT_MODE |NODELIST |CPU_LOAD |PARTITION |PARTITION |ALLOCNODES |STATE |USER |SOCKETS |CORES |THREADS
up|(null)|1|14988|2519|(null)|all|NO|infinite|3765|ip-10-110-79-50|ip-10-110-79-50|1|no|1-infinite|idle|root|16.05|1|1:1:1|0/1 |UNLIMITED |0/1/0/1 |1 |none |0/1/0/1 |(null) |Unknown |1 |n/a |OFF |ip-10-110-79-50 |0.58 |compute* |compute |all |idle |root(0) |1 |1 |1

Thanks for looking into this.

**Comment by mohanasudhan** [comment]
Taking a deeper look at it now. will update the result in few mins

**Pull request closed without merging**
